- platform: mqtt
  name: "Closet Motion"
  state_topic: "tele/bed/binary3"
  payload_on: "ON"
  payload_off: "OFF"
#  availability_topic: "tele/sensors-kitchen/LWT"
#  payload_available: "Online"
#  payload_not_available: "Offline"
  device_class: motion
- platform: template
  sensors:
    closet_occupied:
      friendly_name: "Closet Occupied"
      value_template: "{{ is_state('binary_sensor.closet_motion', 'on') }}"
      device_class: occupancy
      delay_off: !include ../no_motion_delay.yaml
