- platform: mqtt
  name: "Kitchen Motion"
  state_topic: "cmnd/wemos1-motion/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/wemos1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion
- platform: template
  sensors:
    kitchen_occupied:
      friendly_name: "Kitchen Occupied"
      value_template: "{{ is_state('binary_sensor.kitchen_motion', 'on') }}"
      device_class: occupancy
      delay_off: !include ../no_motion_delay.yaml
