homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets

  latitude: 37.7697
  longitude: -122.3933
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
mqtt:
  broker: 127.0.0.1

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  alexa:
    filter:
      exclude_entities:
        - light.bedroom
        - light.living_room
        - light.office
  google_actions:
    filter:
      exclude_entities:
        - light.bedroom
        - light.living_room
        - light.office

zwave:
  usb_path: /zwavestick
  network_key: !secret network_key

light:
  - platform: lifx
  - platform: mqtt
    name: "Office Light"
    state_topic: "stat/sonoff-officelight/POWER"
    command_topic: "cmnd/sonoff-officelight/POWER"
    availability_topic: "tele/sonoff-officelight/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Micke Light"
    state_topic: "stat/sonoff-micke/POWER"
    command_topic: "cmnd/sonoff-micke/POWER"
    availability_topic: "tele/sonoff-micke/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Closet Light"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    state_topic: "stat/sonoff-closet/POWER"
    command_topic: "cmnd/sonoff-closet/POWER"
    brightness_state_topic: "stat/sonoff-closet/Dimmer"
    brightness_command_topic: "cmnd/sonoff-closet/Dimmer"
    brightness_scale: 100
    rgb_command_template: "{{ '%02x%02x%02x00' | format(red, green, blue)}}"
    rgb_state_topic: "stat/sonoff-closet/Color"
    rgb_command_topic: "cmnd/sonoff-closet/Color"
    white_command_template: "{{ '000000%02x' }}"
    white_state_topic: "stat/sonoff-closet/Color"
    white_command_topic: "cmnd/sonoff-closet/Color"
    effect_command_topic: "cmnd/sonoff-closet/Scheme"
    effect_state_topic: "stat/sonoff-closet/Scheme"
    state_value_template: "{{ value }}"
    brightness_value_template: "{{ value }}"
    effect_value_template: "{{ value }}"
    rgb_command_mode: hex
    retain: true
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Desk Light"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    state_topic: "stat/sonoff-desk/POWER"
    command_topic: "cmnd/sonoff-desk/POWER"
    brightness_state_topic: "stat/sonoff-desk/Dimmer"
    brightness_command_topic: "cmnd/sonoff-desk/Dimmer"
    brightness_scale: 100
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_state_topic: "stat/sonoff-desk/Color"
    rgb_command_topic: "cmnd/sonoff-desk/Color"
    white_command_template: "{{ '000000%02x' }}"
    effect_command_topic: "cmnd/sonoff-desk/Scheme"
    effect_state_topic: "stat/sonoff-desk/Scheme"
    state_value_template: "{{ value }}"
    brightness_value_template: "{{ value }}"
    effect_value_template: "{{ value }}"
    rgb_command_mode: hex
    retain: false
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
switch:
  - platform: mqtt
    name: "Ikea Gateway Switch"
    state_topic: "stat/sonoff-ikeagateway/POWER"
    command_topic: "cmnd/sonoff-ikeagateway/POWER"
    availability_topic: "tele/sonoff-ikeagateway/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Custom Switch"
    state_topic: "stat/sonoff-custom/POWER"
    command_topic: "cmnd/sonoff-custom/POWER"
    availability_topic: "tele/sonoff-custom/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
sensor:
  - platform: mqtt
    name: "Remote Temperature"
    state_topic: "tele/wemos1/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "C"
    availability_topic: "tele/wemos1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
  - platform: mqtt
    name: "Remote Humidity"
    state_topic: "tele/wemos1/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
    availability_topic: "tele/wemos1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
  - platform: mqtt
    name: "Remote Illuminance"
    state_topic: "tele/wemos1/SENSOR"
    value_template: "{{ value_json['BH1750'].Illuminance }}"
    unit_of_measurement: "lx"
    availability_topic: "tele/wemos1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: illuminance
  - platform: mqtt
    name: "Office Temperature"
    state_topic: "tele/sonoff-desk/SENSOR"
    value_template: "{{ value_json['DHT22'].Temperature }}"
    unit_of_measurement: "C"
    availability_topic: "tele/sonoff-desk/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
  - platform: mqtt
    name: "Office Humidity"
    state_topic: "tele/sonoff-desk/SENSOR"
    value_template: "{{ value_json['DHT22'].Humidity }}"
    unit_of_measurement: "%"
    availability_topic: "tele/sonoff-desk/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
  - platform: mqtt
    name: "Office Pressure"
    state_topic: "tele/sonoff-desk/SENSOR"
    value_template: "{{ value_json['BMP280'].Pressure }}"
    unit_of_measurement: "hPa"
    availability_topic: "tele/sonoff-desk/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Office Illuminance"
    state_topic: "tele/sonoff-desk/SENSOR"
    value_template: "{{ value_json['BH1750'].Illuminance }}"
    unit_of_measurement: "lx"
    availability_topic: "tele/sonoff-desk/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: illuminance
binary_sensor:
  - platform: mqtt
    name: "Remote Motion"
    state_topic: "cmnd/wemos1-motion/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/wemos1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: motion
  - platform: mqtt
    name: "Office Motion"
    state_topic: "cmnd/desk-motion/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/sonoff-desk/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: motion
input_boolean:
  leo_home:
    name: Leo Home
  emiji_home:
    name: Emiji Home
  night_mode:
    name: Night Mode

tradfri:
  allow_tradfri_groups: false

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    ssh_key: /config/ha_rsa

group: !include groups.yaml
automation: !include_dir_merge_named automation/
script: !include scripts.yaml
