- platform: mqtt
  name: "Remote Temperature"
  state_topic: "tele/wemos1/SENSOR"
  value_template: "{{ value_json['BME280'].Temperature }}"
  unit_of_measurement: "C"
  availability_topic: "tele/wemos1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: temperature
- platform: mqtt
  name: "Remote Humidity"
  state_topic: "tele/wemos1/SENSOR"
  value_template: "{{ value_json['BME280'].Humidity }}"
  unit_of_measurement: "%"
  availability_topic: "tele/wemos1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: humidity
- platform: mqtt
  name: "Remote Pressure"
  state_topic: "tele/wemos1/SENSOR"
  value_template: "{{ value_json['BME280'].Pressure }}"
  unit_of_measurement: "hPa"
  availability_topic: "tele/wemos1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Remote Illuminance"
  state_topic: "tele/wemos1/SENSOR"
  value_template: "{{ value_json['BH1750'].Illuminance }}"
  unit_of_measurement: "lx"
  availability_topic: "tele/wemos1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: illuminance
