alias: Bathroom Occupied
trigger:
  platform: state
  entity_id: binary_sensor.bathroom_occupied
  from: 'off'
  to: 'on'
action:
  service: light.turn_on
  data_template:
    brightness: '{{ 10 if is_state("input_boolean.night_mode", "on") else 255 }}'
    entity_id:
      - light.bathroom_light
