alias: Bathroom Vacated
trigger:
  platform: state
  entity_id: binary_sensor.bathroom_occupied
  from: 'on'
  to: 'off'
action:
  service: light.turn_off
  data:
    entity_id:
      - light.bathroom_light
