alias: Closet Vacated
trigger:
  platform: state
  entity_id: binary_sensor.closet_motion
  from: 'on'
  to: 'off'
action:
  service: homeassistant.turn_off
  data:
    entity_id:
      - light.closet_light
