alias: Closet Occupied
trigger:
  platform: state
  entity_id: binary_sensor.closet_occupied
  from: 'off'
  to: 'on'
action:
  service: homeassistant.turn_on
  data:
    entity_id:
      - light.closet_light
