alias: Emiji Departed
trigger:
  platform: state
  entity_id: device_tracker.emiji_pixel
  from: 'home'
  to: 'not_home'
action:
  service: input_boolean.turn_off
  data:
    entity_id: input_boolean.emiji_home
