alias: Emiji Arrived
trigger:
  platform: state
  entity_id: device_tracker.emiji_pixel
  from: 'not_home'
  to: 'home'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.emiji_home
  - service: light.turn_on
    data:
      entity_id: light.entryway_light
