alias: Kitchen Vacated Day
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_occupied
  from: 'on'
  to: 'off'
condition:
  condition: state
  entity_id: 'input_boolean.night_mode'
  state: 'off'
action:
  service: homeassistant.turn_off
  data:
    entity_id: 
      - switch.switch
