alias: Kitchen Occupied
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_occupied
  from: 'off'
  to: 'on'
condition:
  - condition: state
    entity_id: switch.kitchen_light
    state: 'off'
action:
  service: homeassistant.turn_on
  data:
    entity_id:
      - switch.bar_light
