alias: Kitchen No Motion Night
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion
  from: 'on'
  to: 'off'
  for: !include ../no_motion_delay.yaml
condition:
  condition: state
  entity_id: 'input_boolean.night_mode'
  state: 'on'
action:
  service: homeassistant.turn_off
  data:
    entity_id: 
      - switch.switch_2
