alias: Leo Arrived
trigger:
  platform: state
  entity_id: device_tracker.leo_pixel
  from: 'not_home'
  to: 'home'
action:
  service: input_boolean.turn_on
  data:
    entity_id: input_boolean.leo_home
