alias: Office Vacated
trigger:
  platform: state
  entity_id: binary_sensor.office_occupied
  from: 'on'
  to: 'off'
action:
  service: homeassistant.turn_off
  data:
    entity_id:
      - light.desk_light
